services:
  static-frames:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OUTBOUND_ENDPOINT=http://localhost:3000
    restart: unless-stopped
